package lambda.dynamo.Models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import java.util.ArrayList;

public class Task {
    private String id;
    private String picture;
    private String title;
    private String description;
    private String assignee;
    private String status;
    private ArrayList<History> historyArrayList;

    public Task() {
    }

    /*Getters */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    @DynamoDBAttribute
    public ArrayList<History> getHistoryArrayList() {
        return historyArrayList;
    }

    @DynamoDBAttribute
    public String getPicture() {
        return picture;
    }


    /* Setters */
    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setNewHistory(History history)
    {this.historyArrayList.add(history);}


    public void setHistoryArrayList(ArrayList<History> historyArrayList) {
        this.historyArrayList = historyArrayList;
    }


    public void setPicture(String picture) {
        this.picture = picture;
    }


}
