/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.dynamo;

public class Library {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new Library().getGreeting());
    }
}